# Generated by Django 5.0.1 on 2024-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cimage',
            field=models.ImageField(upload_to='image'),
        ),
    ]
