# Generated by Django 5.0.1 on 2024-01-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_orderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
